theme: jekyll-theme-minimal
title: [Analysis of Reddit comments on political subreddits]
description: [This project aims to study political trends and viewpoints in five of the most popular political subreddits.]
show_downloads: "true"
